# Base configs
baseurl: ""
url: "https://bearmug.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-93020689-1"

# UI configs
title: "PhotograpHi!"
subtitle: "Photos!"
author: "bearmug"
bio: 
publicise: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork Ram repo on github</a>"
web_design: "AJ"
social_urls:
  facebook: 
  twitter: 
  instagram: 
  dribbble: 
  linkedin: 
  github: "https://www.github.com/bearmug"
  
